### ISSUE TITLE
[4.0] Remove dependency on Polymer library

### ISSUE THREAD

**Issue by t2ym** [t2ym/i18n-format#15]
[4.0] Remove dependency on Polymer library

## Status
- Part of https://github.com/t2ym/i18n-element/issues/63
- WIP in [4.0-develop](https://github.com/t2ym/i18n-format/tree/4.0-develop) branch
- NPM package
  - `npm install i18n-format@next` or `npm install i18n-format@4.0.0-pre.13`
    - Depends on `i18n-number@4.0.0-pre`, `wc-putty@0.1.0`, `lit-html@^1.0.0`, `make-plural@^4.3.0`

## Tasks
- [x] Move `@polymer/polymer` from dependencies to devDependencies
- [x] Drop Safari 9 support
- [x] `bower.json` with `BSD-2-Clause` as `license`
- [x] Add `lit-html` dependency
- [x] Convert to `lit-html` rendering
  - [x] Remove `@polymer/polymer` imports
  - [x] Convert properties and observers
- [x] Make these properties read-only
  - [x] `paramAttribute` is `slot`
  - [x] `paramFormat` is `{n}`
  - [x] `observeParams` is `true`
    - [x] Dummy setter for `observeParams`
- [x] Support IE11 and Edge with custom elements v1 polyfill
  - [x] Import a separate `polyfill.js` from an independent npm module for `polyfill.js`
    - [x] Import npm package `wc-putty`
- [x] Convert tests
  - [x] No Polymer methods
  - [x] Adjust some waits
- [x] Convert demo
  - [x] Remove `intl` from `extraDependencies` in `polymer.json`
- [ ] Documentation
  - [x] Decent comments
  - [ ] API Docs page

## Design Issues
- [x] `root` property for `shadowRoot` to imitate a Polymer element
- [x] Is `importMeta` property necessary? No

## Issues
- [x] `document.createElement('i18n-format')` fails with "The result must not have attributes"
  - [x] Fix: Put off setting `this.lang` in the constructor to `connectedCallback()`
- [x] Calling of `_setupParams()` is too early to collect the expected parameters in the local DOM
  - [x] Fix: Put off `this._setupParams()` to `connectedCallback()`
- [x] ShadyDOM misinterprets target of direct `node.appendChild()` as `shadowRoot`
  - Root Cause: If `shadowRoot` is attached, ShadyDOM unexpectedly performs `appendChild()` to `shadowRoot` instead of the node's local DOM
  - [x] Fix: Put off `attachShadow()` to the first rendering
